title: "辉晨雨幕"
description: "辉晨雨幕_辉晨Gloridust的个人博客"
url: https://gloridust.xyz
baseurl: ""
author: "辉晨Gloridust"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs